### ISSUE TITLE
Bug report: [Build 1 | Register ]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#13]
### Issue description

**Test cases ID:  COM_REG101 + CAN_REG107 + COM_REG104 + CAN_REG110 + CC_EXT116**

These tests have been realised on both:
- External - iPhone 13 - 15.6.1 
- iOS simulator - iPhone 15 - 17.4

--- 

**Subscribe:**
|ID|UX|Bug|Problem|
| - | - | - | - |
|1|x||Having to scroll to see the whole register page isn't a good thing|
|2|x||The 'Already ...' is too close to the Subscribe button|
|3|x|x|For the radio buttons, the user should be able to also click on the text and not only the button to select the status|
|4||?|The information written on the subscribe page are automatically transferred to the login page when switching. Is it wanted or not?|
|5||x|The forgot password button is redirected the user to the subscribe page |

### Issue priority

1. Low (Slightly annoying)

### Version

Development

### Steps taken

Just by navigating

### Expected result

1. Maybe shrank the size of the elements
2. Add some margin or padding
3. Make the text clickable
4. Perhaps a feature
5. Some problems are due to the non-existing database

### This issue was tested on a development release

52f31ed

**Comment by Biohazardyee** [comment]
Thanks for your feedback @Clementine951, after a quick look to the issue here's what I can tell you: 

Concerning ID 4: 
It is indeed a feature, from the software side, I only re-use the content inside of the Text Controllers, which are kept in memory on our side, and the user can then log-in more easily after registration. 

ID 5: the forgot password page isn't already implemented, that's why it wasn't working. 

I'll work right away on ID 1 and 2, they are only UI related. 

And finally for ID 3, the backend hasn't been implemented just yet.

**Comment by Clementine951** [comment]
I decided to close this issue because of the opening of a new one. #37
